# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: AQM
channels:
- conda-forge
dependencies:
- sys
- math
- os
- pandas
- PyQt5
- reportlab
- openpyxl
